# Generated by Django 3.1.3 on 2021-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210102_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AV', 'Avon'), ('BE', 'Bedfordshire'), ('BK', 'Berkshire'), ('BU', 'Buckinghamshire'), ('CA', 'Cambridgeshire'), ('CH', 'Cheshire'), ('CV', 'Cleveland'), ('CO', 'Cornwall'), ('CD', 'Cumberland'), ('CU', 'Cumbria'), ('DE', 'Derbyshire'), ('DV', 'Devon'), ('DO', 'Dorset'), ('DU', 'County Durham'), ('EX', 'Essex'), ('GE', 'Gloucestershire'), ('GL', 'Greater London'), ('GM', 'Greater Manchester'), ('HA', 'Hampshire'), ('HE', 'Herefordshire'), ('HT', 'Hertfordshire'), ('HB', 'Humberside'), ('HU', 'Huntingdonshire'), ('IW', 'Isle of Wight'), ('KE', 'Kent'), ('LA', 'Lancashire'), ('LE', 'Leicestershire'), ('LN', 'Lincolnshire'), ('LON', 'London'), ('ME', 'Merseyside'), ('MX', 'Middlesex'), ('NO', 'Norfolk'), ('NH', 'Northamptonshire'), ('ND', 'Northumberland'), ('NT', 'Nottinghamshire'), ('OX', 'Oxfordshire'), ('RU', 'Rutland'), ('SH', 'Shropshire'), ('SO', 'Somerset'), ('ST', 'Staffordshire'), ('SK', 'Suffolk'), ('SU', 'Surrey'), ('SX', 'Sussex'), ('TW', 'Tyne and Wear'), ('WA', 'Warwickshire'), ('WM', 'West Midlands'), ('WE', 'Westmorland'), ('WI', 'Wiltshire'), ('WO', 'Worcestershire'), ('YO', 'Yorkshire')], max_length=100),
        ),
    ]
